apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: my-queue-manager
  namespace: ibm-mq
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  queueManager:
    name: QM1
    storage:
      queueManager:
        type: ephemeral