apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-mq-operator
  namespace: argocd
spec:
  project: ibm-mq
  source:
    repoURL: https://github.com/ZackLaskar/MQ-gitops.git
    path: manifests/ibm-mq-operator
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: ibm-mq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true